### ISSUE TITLE
feature: more edge types

### ISSUE THREAD

**Issue by bjnieuwboer** [damogranlabs/classy_blocks#22]
I've been interested in blockmesh creation codes for a while and I've used and adapted the ofblockmeshdicthelper (https://github.com/takaakiaoki/ofblockmeshdicthelper)

Now, I've been browsing around in your code, and from what I've seen this looks like the best blockmesh creator available! I think you have created a nice framework where extensions are possible. However, the edge type creation is not very flexible. I did miss the feature to use more edge types such as
- a polyline
- the new method in openfoam.com to specify an arc using a center point (https://www.openfoam.com/news/main-news/openfoam-v20-12/pre-processing#pre-processing-blockmesh)
- the arc method of openfoam.org using a axis and angle  (https://github.com/OpenFOAM/OpenFOAM-dev/commit/73d253c34b3e184802efb316f996f244cc795ec6).

The new arc methods allow for a far better readable blockmesh file.

Since you are overhauling the code in the branch: feature/optimization, would this be the right time to add the possibility to use different types of edges?

**Comment by FranzBangar** [comment]
Thanks for your input! I'm always glad to hear this code is useful to someone else.

I had thought about polyline edges before. I'll add that option to the next version (at the moment I can't tell you when exactly).

About different arc edge specifications: so far, classy outputs blockMeshDicts compatible with both versions. Using one or the other edge specification will break compatibility with the other OF version. If it's a matter of readability of blockMeshDicts (keep in mind the whole point of this package is to avoid writing or reading those manually :) ), then center point and angle/axis could be output to a comment next to edge definition.

**Comment by FranzBangar** [comment]
Implemented in the wip/rewrite branch: Arc, Origin, Angle, all output as Arc but the original data still displayed as a comment.

**Comment by bjnieuwboer** [comment]
Thanks for implementing this feature.

**Comment by FranzBangar** [comment]
You can try it out in the wip/rewrite branch but it'll take me a few more days to merge into master
