### ISSUE TITLE
Package info and settings cleanup

### ISSUE THREAD

**Issue by schperplata** [damogranlabs/classy_blocks#25]
[This](https://github.com/damogranlabs/classy_blocks/blob/5b0dad55cd944dddc3ac6f25f0ba20c4152e2df5/.travis.yml) file can be removed. ATM, Travis is not used and CI is configured in GitHub Actions.

Also, new standards are simplifying and unifying some package info. I think __setup.py__ and __requirements-dev.txt__ can be merged to __pyproject.toml__, similar to example [here](https://github.com/damogranlabs/serial-tool/blob/master/pyproject.toml).

Should I look into it?

**Comment by FranzBangar** [comment]
In a jiffy!

**Comment by schperplata** [comment]
Done. 
Inspect some typing issues in tests: https://github.com/damogranlabs/classy_blocks/tree/feature/pkg_files_merge

Other than that it is ready for merge. Notice that now there is no more __setup.py__ and or __requirements.txt__. It is all merged to a __pyproject.toml__. That also changes how development requirements are specified and installed (improved IMO): just install package with `[dev]` extra tag, for example: `python -m pip install -e .[dev]`. 

Additionally, version is only in one place, that is __pyproject.toml__, not in __\_\_init\_\_.py__. 

All package and tools related stuff for classy_block project is now in __pyroject.toml__, except CI configuration, which remains in __tox.ini__ and github __build_ci.yml__. What a wonderful world we live in. 😃

**Comment by schperplata** [comment]
Done f7eb41e2e7b4b7e398b9e66845af200d497b8f6c
