### ISSUE TITLE
Use `pytest` instead of `unittest`

### ISSUE THREAD

**Issue by schperplata** [damogranlabs/classy_blocks#31]
It seems like VS Code test explorer does not know how to handle `@parameterized.*` tests:
![image](https://github.com/damogranlabs/classy_blocks/assets/8736111/8520c577-95bf-4a70-9419-38f45a8e62a6)

By switching to `pytest` framework, you can still write tests in `unittest` format as currently, but VSC will show you also these parametrized sub-tests:
![image](https://github.com/damogranlabs/classy_blocks/assets/8736111/e4d4438c-a34e-4644-9940-d646d3eebe36)
![image](https://github.com/damogranlabs/classy_blocks/assets/8736111/91305d71-eaeb-481d-8d9c-00339a4290fc)

 Let me know if you are interested, I have a branch with these settings are configured, could do PR.

**Comment by FranzBangar** [comment]
That's okay for me, as long as there is no need to rewrite existing 500-ish tests.
