### ISSUE TITLE
classy_blocks on PyPI ?

### ISSUE THREAD

**Issue by paugier** [damogranlabs/classy_blocks#36]
Hi, I discover classy_blocks and I really like it. I'd like to use it in [fluidsimfoam](https://foss.heptapod.net/fluiddyn/fluidsimfoam) but we would need classy_blocks to be uploaded on PyPI.

**Comment by FranzBangar** [comment]
That's feasible.
Is there a specific reason you can't use the _github_ version?

**Comment by paugier** [comment]
Yes. I think it is bad to rely too much on Github. In Python, it is standard to use PyPI (community driven) and not Github.

Moreover, the installation command given in classy_blocks implies having Git installed locally, which should not be required.

It would be much better if classy_blocks could upload source distributions (sdist) and wheels on PyPI.

**Comment by schperplata** [comment]
Yeah, on the long run, this is the way to go for sure.
ATM, there were about 10^6 changes made in a relatively short time, some
even breaking changes, so we just stick with github as a source.

I will take a look and upload latest version to pypi, next week some time.
If you plan to live on the edge with this library, using all the latest and
the greatest features/fixes, I suggest you stick with github source for now.

@kandelabr, we should discuss details on versioning and publishing to PyPi,
version tagging in source code and uploading (publishing) frequency.

**Comment by schperplata** [comment]
https://pypi.org/project/classy-blocks/

@FranzBangar You should keep `master` branch for production and use `develop` branch for development. 
Just create `develop` branch from current commit and we can discuss versioning, merging and publishing to PyPi when you start working again on classy blocks.
