### ISSUE TITLE
Install fails on WSL2

### ISSUE THREAD

**Issue by STK-haan** [damogranlabs/classy_blocks#41]
* classy_blocks version: commit 993b272418618d34264752a9b4014ba9542830e3
* Python version: 3.10.6
* Operating System: Ubuntu 22.04.2 LTS *(Running on WSL2)

### Description
Package name in unrecognizable through pip thus cannot import classy_blocks through python script

### What I Did
Following "How To Use It" section in [README.md](https://github.com/damogranlabs/classy_blocks#readme)

input
`pip install git+https://github.com/damogranlabs/classy_blocks.git`

output
```
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/damogranlabs/classy_blocks.git
  Cloning https://github.com/damogranlabs/classy_blocks.git to /tmp/pip-req-build-6bivehnb
  Running command git clone --filter=blob:none --quiet https://github.com/damogranlabs/classy_blocks.git /tmp/pip-req-build-6bivehnb
  Resolved https://github.com/damogranlabs/classy_blocks.git to commit 993b272418618d34264752a9b4014ba9542830e3
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=1795 sha256=eb42ec936b192297fb6c5aa2a6443e4c2dcb47efa0da358840a97441116e2b06
  Stored in directory: /tmp/pip-ephem-wheel-cache-4g9qqxj0/wheels/9f/5a/bc/716b0a81067ee88b8363d0652c0f9cbd785a48a34a5cf47168
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0
```

After install, when I try to import classy_blocks as cb in .py file: 
`ModuleNotFoundError: No module named 'classy_blocks'`

**Comment by schperplata** [comment]
Try creating virtual environment and install `classy_blocks` there.
Traceback:
`Defaulting to user installation because normal site-packages is not writeable`
… is indicating that you are installing package to user directory. Depending on your environment variables, this directory might or might not be available to python. 

Do other packages from PyPi work when installed in the same way?
Also, what is UNKNOWN and where does it come from?

**Comment by STK-haan** [comment]
> Do other packages from PyPi work when installed in the same way? Also, what is UNKNOWN and where does it come from?

Yes, interestingly other packages work even though same "Defaulting to user installation because normal site-packages is not writeable" is printed to stdout. (Since I installed virtualenv package to create virtual environment, I'm sure about it)

And I'm not sure where the UNKNOWN came from. It dose not appear when I use pip install for other packages like PyFoam.
Anyway, after I source virtual environment, I works without any errors.
