### ISSUE TITLE
help needed to convert PIV data to OpenFoam mesh

### ISSUE THREAD

**Issue by alexlib** [damogranlabs/classy_blocks#5]
Hi, 
thanks for this great piece of software that apparently saves tons of hours for OpenFoam users. I'm here to ask for your advice on a slightly different topic. We work with the particle image velocimetry (open source software, called openpiv-python) and we're interested to convert the measurement results (columns of x,y and 2 components of velocity, u,v) into OpenFOAM boundary conditions or initial conditions over the user - prescribed mesh. 

Seems that your from_points does something very close to what we think is needed. I have no idea about OpenFoam, btw. 

Thanks
Alex @alexlib

**Comment by FranzBangar** [comment]
Hello!

What you're trying to do is two or three layers of code lower than classy_blocks so I don't think this script would be very helpful but I can try pointing you in a direction of sorts.

At the highest level you can use setFields to capture cells and set field values at their location. You'd probably just have to write a script that generates a [setFieldsDict](https://github.com/OpenFOAM/OpenFOAM-5.x/blob/master/tutorials/multiphase/compressibleInterFoam/laminar/depthCharge3D/system/setFieldsDict) with a boxToCell for every measurement point you have. I guess it will be very slow on larger datasets but it is the simplest option that comes to my mind.

The other dirty hack would be that you create a simpler version of your geometry, do the setFields business above, then use mapFields to map your _coarse_ data to a _proper_, finer mesh.

Depending on your programming skills and available time, you could use setFields to generate a full internalField entry in 0/U file. Then you could find the location of each point in internalField and give it the right value from your data using interpolation.

Reading and writing openFoam mesh and field data is reasonably simple, especially when using ascii writeFormat.
See mesh description: https://www.openfoam.com/documentation/user-guide/4-mesh-generation-and-conversion/4.1-mesh-description

I'm sorry but that's all I can say from the top of my head. A good option would be to ask in the [OpenFOAM forum on CFD online](https://www.cfd-online.com/Forums/openfoam/), there's a lot of experienced users there. Also there's an OF discord chat channel free for anyone to join: https://discord.gg/P9p9eHn

I guess you'll get more relevant and detailed information there.

Good luck!

**Comment by alexlib** [comment]
Thanks a lot @FranzBangar
