### ISSUE TITLE
T-joint implementation

### ISSUE THREAD

**Issue by MaguRaam** [damogranlabs/classy_blocks#51]
Hi,  I noticed that the T-joints still need to be implemented. Do you have any rough implementations of T-joints? Or can you guide me through how to implement it myself?

Thank you

**Comment by FranzBangar** [comment]
I guess one should start with a SemiCylinder but one face should be inclined at 45 degrees. The easiest would be if there was a skew transform so I guess that would be the first thing to add.
Then, everything else is just copy/rotate/mirror.

Note that a T-joint is a sort of collection of Shapes so it's nothing like current classes (Operation, Shape, Stack). I guess this still requires some thought.

What do you have in mind?

**Comment by MaguRaam** [comment]
Thank you for the response. I will think about your idea, try implementing it, and see where it goes.

**Comment by bjnieuwboer** [comment]
This might be a nice starting point: "pipeline mesh generator based on blockmesh"
https://oar.ptb.de/files/download/530.20230512.pdf

Although I don't know how well the code is documented using equations.

**Comment by MaguRaam** [comment]
Fantastic, this will be helpful to me. I will start scripting and get things done, and once I have everything, I will discuss the object-oriented framework. As I have a lot of  features in my geometry

1) T-joint
2) Pipe branches to two pipes
3) multiple pipes merge in one big cylinder

Thank you.

**Comment by FranzBangar** [comment]
I suggest:
- Add a shear transform to ElementBase
- Create a 'private' SemiCylinder Shape with an (arbitrarily) tilted end face
- Make a new entity type, 'Assembly', that holds multiple Shapes
- Create Assemblies, starting with a T-joint and expanding to other stuff

**Comment by FranzBangar** [comment]
Check out the [feature/assembly branch](https://github.com/damogranlabs/classy_blocks/commit/bd9bfbf1418dea91291ccdcd2bc49b70fa26bdf6). I whipped a rough draft of what I suppose T-joint might look like. Read through the commit message to see what's left to be done. Next week I'll be on holidays, hence - offline.

**Comment by MaguRaam** [comment]
Hello, this is nice. I'll be sure to see how I can take it from here with my rusty Python knowledge. 

Have a nice holiday

**Comment by FranzBangar** [comment]
Aye. I'm working on a nicer way of doing _everything_ now. Looks like the final implementation will be far from the initial makeshift stuff.

**Comment by FranzBangar** [comment]
Merged new stuff with the development branch - T-joint, L-joint (a sharp elbow) and an arbitrary N-joint. Will be pushed into master after some more testing.
![image](https://github.com/user-attachments/assets/24428750-ea50-49dd-a4dc-3815581bef89)
Next, the cylinder thing. This is a bit more complicated one.

**Comment by MaguRaam** [comment]
This looks fantastic. Thanks a lot.
