### ISSUE TITLE
Failing to run the development version of tank.py

### ISSUE THREAD

**Issue by hfrusinque** [damogranlabs/classy_blocks#67]
* classy_blocks version: 1.6.4
* Python version: 3.11.5 on Anaconda
* Operating Systems: for both Ubuntu 22.04.5 LTS and Windows 10

Failing to run the development version of tank.py with:   
```shell
>> python tank.py

File "/...../python_scripts/tank.py", line 19, in <module>
    from classy_blocks.grading.autograding.grader import SimpleGrader
ModuleNotFoundError: No module named 'classy_blocks.grading.autograding'
``` 

after successfully installing  the development version of classy_blocks:

```shell
>> pip install git+https://github.com/damogranlabs/classy_blocks.git@development 
                                                                                                        
Collecting git+https://github.com/damogranlabs/classy_blocks.git@development                                               
  Cloning https://github.com/damogranlabs/classy_blocks.git (to revision development) to /tmp/pip-req-build-i_j5bj8_       
  Running command git clone --filter=blob:none --quiet https://github.com/damogranlabs/classy_blocks.git /tmp/pip-req-build-i_j5bj8_                                                                                                                  
  Resolved https://github.com/damogranlabs/classy_blocks.git to commit 8d9cbb9a8a5ba84f3be4c505461fbb9e24af602d            
  Installing build dependencies ... done                                                                                   
  Getting requirements to build wheel ... done                                                                             
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /home/administrator/miniconda3/lib/python3.11/site-packages (from classy_blocks==1.6.4) (1.26.2)
Requirement already satisfied: scipy in /home/administrator/miniconda3/lib/python3.11/site-packages (from classy_blocks==1.6.4) (1.11.4)
Requirement already satisfied: nptyping in /home/administrator/miniconda3/lib/python3.11/site-packages (from classy_blocks==1.6.4) (2.5.0)

**Comment by FranzBangar** [comment]
Can you locate actual downloaded source in `site-packages` and see that `grading/autograding/grader.py` is really there?
I have done the same as you reported on my system but don't have any problems with that example...

**Comment by FranzBangar** [comment]
Also, can you try installing in 'editable' mode, that is `pip install -e ...`?

**Comment by hfrusinque** [comment]
thanks for your reply 

> Can you locate actual downloaded source in `site-packages` and see that `grading/autograding/grader.py` is really there? I have done the same as you reported on my system but don't have any problems with that example...

The 'autograding' folder was not there, after a uninstalling and installing the the "git" development version again, the folder was created but running the tank script fails with:

```shell
>>python tank.py

Traceback (most recent call last):
  File "/home/administrator/Documents/python_scripts/tank.py", line 18, in <module>
    import classy_blocks as cb
  File "/home/administrator/miniconda3/lib/python3.11/site-packages/classy_blocks/__init__.py", line 2, in <module>
    from .construct.assemblies.joints import LJoint, NJoint, TJoint
  File "/home/administrator/miniconda3/lib/python3.11/site-packages/classy_blocks/construct/assemblies/joints.py", line 6, in <module>
    from classy_blocks.construct.assemblies.assembly import Assembly
  File "/home/administrator/miniconda3/lib/python3.11/site-packages/classy_blocks/construct/assemblies/assembly.py", line 7, in <module>
    from classy_blocks.construct.operations.operation import Operation
  File "/home/administrator/miniconda3/lib/python3.11/site-packages/classy_blocks/construct/operations/operation.py", line 5, in <module>
    from typing_extensions import Unpack
ModuleNotFoundError: No module named 'typing_extensions'

```  

I'm going to try the recommendation from your second response

**Comment by hfrusinque** [comment]
> Also, can you try installing in 'editable' mode, that is `pip install -e ...`?

after doing that, I get the following error:

```shell
>> pip install -e git+https://github.com/damogranlabs/classy_blocks.git

ERROR: Could not detect requirement name for 'git+https://github.com/damogranlabs/classy_blocks.git', please specify one with #egg=your_package_name

```

**Comment by hfrusinque** [comment]
uninstalling and re-installing on Ubuntu got me the error I described above. However, the same _did_ work on Windows

**Comment by hfrusinque** [comment]
should I close the issue?

**Comment by FranzBangar** [comment]
Can you sketch your desired geometry? I can't visualize what exactly do you mean. A T-joint could be easily closed by hemispheres but if you need a tank with inlet/outlet of a smaller diameter, that will massively complicate blocking scheme. It's doable, though, but not with current objects.

I won't investigate the matter into detail as the autograding feature is still incomplete. Once I get it working, I'll push it into master branch together with a new version, direct (top-level) imports, tests etc. Until then, you can use the old-school way of chopping (see examples of previous versions - currently master is among them).
